//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMng.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DiningMngEntities : DbContext
    {
        public DiningMngEntities()
            : base("name=DiningMngEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dn_authority> dn_authority { get; set; }
        public DbSet<dn_eventLog> dn_eventLog { get; set; }
        public DbSet<dn_groupAuthority> dn_groupAuthority { get; set; }
        public DbSet<dn_groups> dn_groups { get; set; }
        public DbSet<dn_groupUser> dn_groupUser { get; set; }
        public DbSet<dn_users> dn_users { get; set; }
        public DbSet<dn_deleted_images> dn_deleted_images { get; set; }
        public DbSet<dn_dishes> dn_dishes { get; set; }
        public DbSet<dn_desks> dn_desks { get; set; }
        public DbSet<dn_order> dn_order { get; set; }
        public DbSet<dn_orderEntry> dn_orderEntry { get; set; }
        public DbSet<dn_discountInfo> dn_discountInfo { get; set; }
        public DbSet<dn_discountInfoUsers> dn_discountInfoUsers { get; set; }
        public DbSet<dn_points> dn_points { get; set; }
        public DbSet<dn_pointsForDish> dn_pointsForDish { get; set; }
        public DbSet<dn_pointsRecord> dn_pointsRecord { get; set; }
        public DbSet<dn_pointsForDishRecord> dn_pointsForDishRecord { get; set; }
        public DbSet<dn_birthdayMealLog> dn_birthdayMealLog { get; set; }
        public DbSet<ei_users> ei_users { get; set; }
        public DbSet<dn_Restaurent> dn_Restaurent { get; set; }
        public DbSet<dn_items> dn_items { get; set; }
        public DbSet<vw_getHRDeps> vw_getHRDeps { get; set; }
        public DbSet<vw_getHREmps> vw_getHREmps { get; set; }
    
        public virtual ObjectResult<SearchHREmp_Result> SearchHREmp(string searchValue)
        {
            var searchValueParameter = searchValue != null ?
                new ObjectParameter("searchValue", searchValue) :
                new ObjectParameter("searchValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchHREmp_Result>("SearchHREmp", searchValueParameter);
        }
    }
}
