//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dn_birthdayMealLog
    {
        public int id { get; set; }
        public string year { get; set; }
        public string user_no { get; set; }
        public string birthday { get; set; }
        public Nullable<System.DateTime> op_date { get; set; }
        public Nullable<bool> is_cancelled { get; set; }
        public string dish_name { get; set; }
    }
}
