//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dn_discountInfoUsers
    {
        public int id { get; set; }
        public Nullable<int> discount_id { get; set; }
        public string suit_user_no { get; set; }
        public string suit_user_name { get; set; }
        public Nullable<int> has_discount_times { get; set; }
    
        public virtual dn_discountInfo dn_discountInfo { get; set; }
    }
}
