//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dn_desks
    {
        public int id { get; set; }
        public string number { get; set; }
        public Nullable<int> seat_qty { get; set; }
        public Nullable<bool> can_seat_together { get; set; }
        public string open_weekday { get; set; }
        public string open_time { get; set; }
        public Nullable<bool> is_cancel { get; set; }
        public Nullable<int> create_user { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> last_update_time { get; set; }
        public string belong_to { get; set; }
        public string name { get; set; }
    
        public virtual dn_users dn_users { get; set; }
    }
}
