//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dn_discountInfo
    {
        public dn_discountInfo()
        {
            this.dn_discountInfoUsers = new HashSet<dn_discountInfoUsers>();
        }
    
        public int id { get; set; }
        public Nullable<decimal> resume_bigger_than { get; set; }
        public Nullable<decimal> minus_price { get; set; }
        public Nullable<decimal> discount_rate { get; set; }
        public Nullable<bool> for_everyone { get; set; }
        public Nullable<System.DateTime> from_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string create_no { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string comment { get; set; }
        public string discount_name { get; set; }
        public Nullable<int> has_benefit_times { get; set; }
        public string res_no { get; set; }
    
        public virtual ICollection<dn_discountInfoUsers> dn_discountInfoUsers { get; set; }
    }
}
