//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dn_eventLog
    {
        public int id { get; set; }
        public string user_name { get; set; }
        public string ip { get; set; }
        public Nullable<System.DateTime> op_time { get; set; }
        public string model { get; set; }
        public string sys_num { get; set; }
        public string @event { get; set; }
        public Nullable<int> unusual { get; set; }
        public Nullable<int> user_id { get; set; }
    }
}
