//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dn_groupUser
    {
        public int id { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual dn_groups dn_groups { get; set; }
        public virtual dn_users dn_users { get; set; }
    }
}
