//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dn_groups
    {
        public dn_groups()
        {
            this.dn_groupAuthority = new HashSet<dn_groupAuthority>();
            this.dn_groupUser = new HashSet<dn_groupUser>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<dn_groupAuthority> dn_groupAuthority { get; set; }
        public virtual ICollection<dn_groupUser> dn_groupUser { get; set; }
    }
}
