//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dn_orderEntry
    {
        public int id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> disk_id { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<bool> is_done { get; set; }
        public Nullable<System.DateTime> done_time { get; set; }
        public string benefit_info { get; set; }
    
        public virtual dn_dishes dn_dishes { get; set; }
        public virtual dn_order dn_order { get; set; }
    }
}
