//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dn_points
    {
        public int id { get; set; }
        public string user_no { get; set; }
        public string user_name { get; set; }
        public int points { get; set; }
        public string res_no { get; set; }
    }
}
