//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dn_users
    {
        public dn_users()
        {
            this.dn_groupUser = new HashSet<dn_groupUser>();
            this.dn_dishes = new HashSet<dn_dishes>();
            this.dn_desks = new HashSet<dn_desks>();
        }
    
        public int id { get; set; }
        public string user_name { get; set; }
        public string real_name { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> register_date { get; set; }
        public Nullable<bool> is_forbit { get; set; }
        public Nullable<System.DateTime> last_login_date { get; set; }
        public string role { get; set; }
        public Nullable<int> fail_times { get; set; }
    
        public virtual ICollection<dn_groupUser> dn_groupUser { get; set; }
        public virtual ICollection<dn_dishes> dn_dishes { get; set; }
        public virtual ICollection<dn_desks> dn_desks { get; set; }
    }
}
