//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_getHREmps
    {
        public int dept_id { get; set; }
        public string emp_no { get; set; }
        public string emp_name { get; set; }
        public string sex { get; set; }
        public string id_code { get; set; }
        public string job { get; set; }
        public string tel { get; set; }
        public string job_type { get; set; }
    }
}
